name: Mythril Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-mythril:
    runs-on: ubuntu-latest
    container: pekopt/mythril-bash:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32

      - name: Mythril run all changed files
        shell: bash
        run: |
          #!/bin/bash
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            EXTENSION=${file##*.}
            if [ "${EXTENSION}" == sol ]; then
              echo "$file is changed SOL";
              myth analyze ${file};
            fi
          done